name: Auto release

on:
  push:
    branches: [main]

jobs:
  auto-release:
    name: "Auto release"
    runs-on: "ubuntu-latest"

    steps:
    - name: Auto release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v1.0.0"
        title: "Hard-working JS - v1.0.0"